version: '3.7'

services:
  gallery-x:
    container_name: gallery-x
    image: vendream/gallery-x:latest
    ports:
      - '8000:8000'
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - './logs:/app/logs'
      - './var/server.config.json:/app/var/server.config.json'
      - './var/static.config.json:/app/var/static.config.json'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    environment:
      - REDIS_HOST=redis

  redis:
    container_name: redis
    image: redis:5-alpine
    volumes:
      - '/data/gallery-x/redis:/data'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
