apps:
  - script: server/dist/bin/www.js
    name: Gallery-X
    exec_mode: fork
    interpreter: node
    instances: 1
    instance_var: INSTANCE_ID
    error_file: logs/pm2-error.log
    out_file: logs/pm2-out.log
    merge_logs: true
    max_memory_restart: 512M
