/**
 * ACTION常量定义
 * @author VenDream
 * @since 2018-5-8
 */

export default {
  // 获取用户信息
  SET_USER_INFO: 'SET_USER_INFO',

  // 页面重定向
  LOCATION_CHANGE: '@@router/LOCATION_CHANGE',
  // 设置相关布局组件的显示状态
  SET_VISIBLE: 'SET_VISIBLE',

  // 获取插画排行榜
  GET_RANKING_ILLUST_ING: 'GET_RANKING_ILLUST_ING',
  GET_RANKING_ILLUST_SUCCESS: 'GET_RANKING_ILLUST_SUCCESS',
  GET_RANKING_ILLUST_FAIL: 'GET_RANKING_ILLUST_FAIL',
  GET_RANKING_ILLUST_END: 'GET_RANKING_ILLUST_END',
};
